## R script for looping through the htseq outputs and merging them into one matrix

summarize_sample_counts <- function(input_count_files, sample_names) {
	# Loop through files and collect them in a list
	cov <- list()
	for (i in 1:length(input_count_files)) {
		# Load files
		count_file <- input_count_files[i]
		sample_name <- sample_names[i]

		# Import into our list and set col names
		cov[[i]] <- read.table(count_file, sep="\t", header=FALSE, stringsAsFactors=FALSE)
		colnames(cov[[i]]) <- c("ENSEMBL_GeneID", "GeneSymbol", sample_name)
	}

	## construct one data frame from list of data.frames using reduce function
	# Reduce: Takes function and vector, then applies function to first two elements of vector, then result of that to third element, etc.
	df <- Reduce(function(x,y) merge(x = x, y = y, by =c("ENSEMBL_GeneID", "GeneSymbol")), cov)

	return(df)
}


main_function <- function() {
	# Input count files (generated by htseq-count)
	input_count_files <- snakemake@input[["sample_count_files"]]
	# Sample names
	sample_names <- snakemake@params[["sample_names"]]
	# Output file
	output_total_counts_table <- snakemake@output[["total_counts_table"]]

	# Additional count file
	# additional_count_file <- snakemake@params[["additional_count_file"]]

	# 1. Collect all counts
	total_counts <- summarize_sample_counts(input_count_files , sample_names)

	# 2. Add additional counts -> This is merged with inner joint!
	# if (addtional_count_file != NULL && additional_count_file != "NA" && additional_count_file != "") {
	# 	additional_counts <- read.table(additional_count_file, sep="\t", header=TRUE, stringsAsFactors=FALSE)
	# 	print(paste(c("First row lenght:"), length(additional_counts[1,])))
	# 	print(paste(c("Second row length:"), length(additional_counts[2,])))
	# 	# Remove suffixes of form "[1-9]?_[1-9]? from first column
	# 	additional_counts$geneID <- gsub(".[0-9]+_[0-9]+$", "", additional_counts$geneID)
	# 	print(paste(c("First row lenght:"), length(additional_counts[1,])))
	# 	print(paste(c("Second row length:"), length(additional_counts[2,])))
	# 	total_counts <- merge(x = total_counts, y = additional_counts, by.x="ENSEMBL_GeneID", by.y="geneID")
	# 	print(paste(c("First row lenght:"), length(total_counts[1,])))
	# 	print(paste(c("Second row length:"), length(total_counts[2,])))
	# }

	## 3. write to file
	write.table(total_counts, output_total_counts_table, sep="\t", quote=FALSE, row.names=FALSE)
	sanity_check <- read.table(output_total_counts_table, sep="\t", header=TRUE, stringsAsFactors=FALSE)
	print(paste(c("First row lenght:"), length(sanity_check[1,])))
	print(paste(c("Second row length:"), length(sanity_check[2,])))
}

# Run main
main_function()
